### ISSUE TITLE
How could a endpoint looks like?

### ISSUE THREAD

**Issue by JohannesKonings** [SAP/devops-cm-client#18]
Is it just a IP and port of the SAP-System or is somthing to add (e.g. /sap/bc/adt)?

![image](https://user-images.githubusercontent.com/14806640/47618064-ec74dd00-dace-11e8-9aa7-efe8d97f39da.png)

Thanks

**Comment by marcusholl** [comment]
Thank you very much for your interest in our project.

* When used in conjunction with SAP-SolutionManager the endpoint looks like: `<protocol>://<host>:<port>/sap/opu/odata/SAP/AI_CRM_GW_CM_CI_SRV`
* When used in conjunction with CTS the endpoint looks like: `<protocol>://<host>:<port>/sap/opu/odata/SAP/SCTS_CLOUD_API_ODATA_SRV`

Best regards

**Comment by JohannesKonings** [comment]
Thanks for the info.
Unfortunately, I can't find a service SCTS_CLOUD_API_ODATA_SRV on our NW7.52.
What are the prerequisite for that?

**Comment by radsoulbeard** [comment]
We will check it with our colleagues and come back to you.

**Comment by radsoulbeard** [comment]
SCTS_CLOUD_API_ODATA_SRV  will be available with NW7.52 SP03

**Comment by JohannesKonings** [comment]
OK, thanks.
Any plans to downport? NW7.52 SP03 is far away for me :)

**Comment by radsoulbeard** [comment]
Not as far as I know. But this is something you should discuss with your account executive for your NW stack.

**Comment by JohannesKonings** [comment]
OK, thanks for the info

**Comment by sabatale** [comment]
> Thank you very much for your interest in our project.
> 
> * When used in conjunction with SAP-SolutionManager the endpoint looks like: `<protocol>://<host>:<port>/sap/opu/odata/SAP/AI_CRM_GW_CM_CI_SRV`
> * When used in conjunction with CTS the endpoint looks like: `<protocol>://<host>:<port>/sap/opu/odata/SAP/SCTS_CLOUD_API_ODATA_SRV`
> 
> Best regards

Hello,

I apologize for the necro-reply, but here it goes! Would you be able to confirm whether these 2 endpoints are still valid? I am unable to find any of those in SAP Solution Manager SP10 (SICF, /IWFND/MAINT_SERVICES) - unless there are precise prerequisites in order to deploy them?

Thanks!

**Comment by radsoulbeard** [comment]
Dear @sabatale ,
we got the confirmation, that there was no change. If you have trouble I recommend to open an SAP ticket for your system.
Best regards!

**Comment by sabatale** [comment]
It was solved pretty quickly through OSS. Thank you for your instant feedback :)
