### ISSUE TITLE
Source code for SCTS_CLOUD_API_ODATA_SRV

### ISSUE THREAD

**Issue by Srinu3366** [SAP/devops-cm-client#22]
Can we get source code for SCTS_CLOUD_API_ODATA_SRV as a git package so that we can download to 7.52 SP01 version to work with this CLI tool. Is there any dependency other that this service?

**Comment by 1084565** [comment]
Unfortunately we can not do that. 
What is your scenario? Could you maybe use an RFC solution as a fallback?

https://github.com/SAP/jenkins-library/pull/449

**Comment by Srinu3366** [comment]
We trying to release the transports from Azure DevOps pipelines. We are using ABAP Git to commit the code to a git repository and then running unit tests from the pipeline. We want to release the transport in ABAP system from the pipeline if the unit tests are successful.

**Comment by 1084565** [comment]
As an alternative for your 7.52 SP01 you could try RFC communication instead. We have a Dockerfile that can help you to realease TRs from your pipeline: https://github.com/SAP/devops-docker-images/tree/master/node-rfc
Would that work for you?

**Comment by Srinu3366** [comment]
I will try using this and post an update here.

**Comment by radsoulbeard** [comment]
As there was no update since nearly 2 months I close the issue.
