### ISSUE TITLE
Question: do you plan to add suport for ADT endpoint?

### ISSUE THREAD

**Issue by jfilak** [SAP/devops-cm-client#30]
ADT provides Transport Management API too and it is enabled almost everywhere.

I added some initial implementation at:
https://github.com/jfilak/sapcli/blob/master/doc/commands.md#change-transport-system-cts

I planned to add more features in future, but if you push this project forward, I would have more time working on other things.

**Comment by radsoulbeard** [comment]
Yes we have planned to look into it, but there is no decision taken so far. We are more SAP Cloud Platform driven as this cm_client is part of our [Project "Piper"](https://github.com/SAP/jenkins-library). The transport system is for us just another deploy target at the moment.

**Comment by marcusholl** [comment]
Are there any follow-up questions or can we close this thread?

**Comment by jfilak** [comment]
No from my side. I just wanted to make you aware of my attempts in the field of controlling CTS via a tool usable from command line (e.g. in Jenkins).
