### ISSUE TITLE
No development-system-id parameter in create-transport command (Version 1.0.0, SOLMAN Backend Type)

### ISSUE THREAD

**Issue by devhirsbrunnerm** [SAP/devops-cm-client#36]
Hello,

according to the README you should use version 1.0.0 with SAP Solution Manager 7.2 SP6, SP7. 
It does not seem possible to give the development system id as a parameter (with Backend Type SOLMAN), when calling the create-transport command (According to the help output and the source code). 

How can I specify the development system id with version 1.0.0 of the cm-client tool when creating a transport?

Thanks for the help!

**Comment by radsoulbeard** [comment]
Hello,

development system id was introduced with version 2.0.0 and should only be needed with Solution Manager 7.2 >= SP8.
If you get an error with the cmclient please provide the call stack for further investigation.

Thanks in advance!

**Comment by marcusholl** [comment]
See also  https://launchpad.support.sap.com/#/notes/2621747

**Comment by devhirsbrunnerm** [comment]
Hello, 
thanks for the quick replies!
I was more interested in wheter there is a way with this version of the cmclient to specify which system the transport goes to. 

When trying to access the link I get the following error:
"You are not entitled to access SAP Note/KBA 2621747."

I recently learned, that we will update our Solution Manager version soon, therefore the issue is not really relevant for me anymore. Shall i close the issue or leave it until a conclustion is found (in case someone stumbles upon the same problem in the future)?

Thanks!
