### ISSUE TITLE
Running cmclient on Windows 10

### ISSUE THREAD

**Issue by BrendanFarthing** [SAP/devops-cm-client#37]
Hi,

Is it possible to run cmclient on Windows 10? Looking at the file it looks like a unix bash script.
Do you have a Windows batch file that can achieve the same natively in Windows 10 ?

Thanks,

Brendan

**Comment by radsoulbeard** [comment]
Hi Brendan,
no we do not plan and do not have a Windows batch file for it. We use it in a Linux based docker container.
If you have a need for it, please feel free to contribute.

Regards,
Thorsten

**Comment by BrendanFarthing** [comment]
Hi Thorsten,
Ok thanks for the info. We are looking at integrating this with Microsoft Azure DevOps pipelines and use a connected Windows VM with an Azure Pipelines Agent to run custom clients like this. If we go ahead with that we'll contribute our Windows script.

Regards,
Brendan

**Comment by 1084565** [comment]
Hi Brendan,
just out of curiosity, why don't you run this on a Ubuntu VM on Azure Devops directly?

Christoph

**Comment by BrendanFarthing** [comment]
Hi Christoph,
Not my choice, unfortunately. I have to work with the corporate infrastructure setup by others which I have no control over. So a specific Windows VM is my only choice for Azure DevOps.

Brendan
