### ISSUE TITLE
Unable to find valid certification path

### ISSUE THREAD

**Issue by yramamurthy** [SAP/devops-cm-client#42]
Hi,
I am using 2.0.1 version of cmclient to put up a CI/CD pipeline to deploy SAP UI5 application into SAP FrontEndServer with OData. While testing the cmclient, i get the following error:

_

> Exception in thread "main" javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

_

the command issue is this:

> ./dist.cli-2.0.1/bin/cmclient --endpoint "https://host:port" --password 'xxx' --backend-type CTS --user "xxx" create-transport -tt "K" -d "test" -ts "XS0"

How do I overcome this error?

**Comment by radsoulbeard** [comment]
I assume your endpoint has a self signed certificate or a company internal certification path. As the cmclient is a java application you need to add the certificate chain into the java trust store with the keytool.

**Comment by yramamurthy** [comment]
Thank you for the clarification. closing the issue.

**Comment by noellowry** [comment]
@yramamurthy I am wondering how you solved this issue? I am facing the same issue trying to use image in jenkins setup. I tried to add certs to keystore and use that docker image but it still fails. Would be great to get any tips on how to solve :)
