### ISSUE TITLE
Service not available

### ISSUE THREAD

**Issue by luisaugustogodoy** [SAP/devops-cm-client#50]
We have 2 environments, Solman 7.2 with SP9 and another SAP_UI 7.54 SP 3.
In none we have this service available:
SCTS_CLOUD_API_ODATA_SRV

Please, any clues? With these pre-requisites, shouldn't this OData service be available?

Thanks

**Comment by radsoulbeard** [comment]
For the Solman connection please use the following end point:
<protocol>://<host>:<port>/sap/opu/odata/SAP/AI_CRM_GW_CM_CI_SRV

At the moment we have an issue with SCTS_CLOUD_API_ODATA_SRV as it does not work as expected.

**Comment by luisaugustogodoy** [comment]
Thanks for the quick response, but also not available in our systems.
Is there any procedure to be done to find and activate the OData? Should we open an OSS ticket?

**Comment by radsoulbeard** [comment]
Hi @luisaugustogodoy ,
Yes, please open an OSS ticket if the ODATA Service is not activated and you need help to activate it.

Best regards !
