### ISSUE TITLE
Integrating CM Client with ChaRM/Solman 7.2 sp10

### ISSUE THREAD

**Issue by Berrrtz** [SAP/devops-cm-client#51]
It seems there's a lack of documentation around the CM Client integration with ChaRM/Solman. Using the CM Client, we are not sure which service/end-point to call in SolMan and whether or not the service is ready, as we are not getting any result while calling the AI_CRM_GW_CM_CI_SRV service. Could you please advise and point us in the right direction with this issue? It also shows that this out of the box service AI_CRM_GW_CM_CI_SRV is not supported by SAP.

**Comment by radsoulbeard** [comment]
Hi @Berrrtz ,
For the Solman connection please use the following end point:
<protocol>://<host>:<port>/sap/opu/odata/SAP/AI_CRM_GW_CM_CI_SRV

If you need help enabling it, please open an SAP ticket for Solution Manager.

Best regards
