### ISSUE TITLE
Not Working OData 'SCTS_CLOUD_API_ODATA' URI Options

### ISSUE THREAD

**Issue by kaaaaaak** [SAP/devops-cm-client#53]
In following case, $filter and $orderby options is not working.
1. Specify multiple parameters 'Id' for $filter
2. Specify 'Type' for $filter
3. Using $orderby

I debuged it OData service, avobe probrems cause is below.
1. Specify multiple parameters 'Id' for $filter
Class 'IF_CTS_CLOUD_TRANSPORT_ENT_FAC' Method 'get_entity_table_by_selection' line 290-299.
When multiple IDs are specified, only the leading 'ID' string is replaced. (Same as other items)

2. Specify 'Type' for $filter
Class 'IF_CTS_CLOUD_TRANSPORT_ENT_FAC' Method 'get_entity_table_by_selection' line 290-299.
It's area doesn't has "replace 'TYPE' xxxxx" statement.

3. Using $orderby
Class 'IF_CTS_CLOUD_TRANSPORT_ENT_FAC' Method 'get_entity_table_by_selection' line 361.
A fixed column is specified in the SQL orderby statement.

Environment:
 S/4HANA : 1909
 7.54, SP00

**Comment by radsoulbeard** [comment]
Hi @kaaaaaak ,
what is your use case ?

Best regards

**Comment by radsoulbeard** [comment]
No answer since a month.
