### ISSUE TITLE
[Question] Is it possible to access the oData services directly

### ISSUE THREAD

**Issue by sabatale** [SAP/devops-cm-client#55]
(This is not directly related to the devops client)

I was wondering whether it is possible to send requests to the endpoint directly without using the CLI? for example, to create or import a request

I was not able to find documentation on what the request payload should look like to send a POST (I assume) request to:

- /sap/opu/odata/sap/SCTS_CLOUD_API_ODATA_SRV
- /sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV

**Comment by sabatale** [comment]
For those looking for an answer for SCTS_CLOUD_API_ODATA_SRV as of SAP_UI 753, however I am not able to find the property for setting the Transport Type (Customizing, Development) or the client?

(assuming this is public information? otherwise feel free to remove)

```
**../sap/opu/odata/sap/SCTS_CLOUD_API_ODATA_SRV/Transports**

-<content type="application/xml">

-<m:properties>

<d:Id>SIDK900000</d:Id>

<d:Type>K</d:Type>

<d:Status>D</d:Status>

<d:TarSystem/>

<d:Owner>User</d:Owner>

<d:Date>2020-08-17T00:00:00</d:Date>

<d:Time>PT15H17M34S</d:Time>

<d:RequestRef/>

<d:Description/>

<d:Cloud>X</d:Cloud>

</m:properties>
```

**Comment by sabatale** [comment]
I found my information here: [https://api.sap.com/api/API_TRANSPORT_MANAGEMENT/](https://api.sap.com/api/API_TRANSPORT_MANAGEMENT/)

However is it possible to specify a client when creating a request?

**Comment by marcusholl** [comment]
> I was wondering whether it is possible to send requests to the endpoint directly without using the CLI?

Yes, this is technically possible, of course.
But maybe it is simpler to use the client for that? I assume introducing the client in an environment comes with less efforts compared to making the requests manually. But that is maybe opinionated.

> However is it possible to specify a client when creating or importing a request?

Don't know the details by heart. Maybe you can do some reverse-engineering with the client since the client is supposed to send the appropriate requests.

**Comment by sabatale** [comment]
@marcusholl Using the oData through API was simply more fitting our environment, but I totally agree with you for most cases.

However we are still unsure how the TarSystem is mapped to the request through the client. For example, setting ABC.100 (SYS.CLIENT) while creating a request results in no Target System in the request in the backend. Also, if the target system happens to be a Target Group, the creation seems to fail because it is not recognized as a target.

Is this normal behaviour? In other words, do our users need to manually set the target group or client after creation?

E.g. Sending the POST with TarSystem = NPL.100 only retains NPL in the backend

![image](https://user-images.githubusercontent.com/50220345/96495104-584d3480-1215-11eb-9094-20a6271da4fa.png)

E.g; Updating the Target Group manually in the backend is not reflected when performing a GET with the client

![image](https://user-images.githubusercontent.com/50220345/96494990-2cca4a00-1215-11eb-85c6-e96d8ca8cb93.png)

**Comment by radsoulbeard** [comment]
Hi @sabatale 

as Marcus mentioned we are not very deep in all functionalities of the API. I would suggest you open a customer message for the ABAP transport component.

Best regards,
Thorsten
