### ISSUE TITLE
The error occurred when Fiori apps upload to ABAP system using CI

### ISSUE THREAD

**Issue by tomocci** [SAP/devops-cm-client#66]
I created the cm client using docker.
And I executed the below command.
fiori deploy --noConfig -t XXXXXXX -u https://XXXXXXX.XXXX:XXXX -p ZXX01 -n ZFIORIDEMO -l nnn -e "FioriDeployTest" -y --username ABAP_USER --password ABAP_PASSWORD

So I got this errors.
-----ERROR Message---------
ERR! builder:custom deploy-to-abap Request failed with status code 400
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Running in regular mode, brief log
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap 16 Files found in Archive.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Parameters *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap The text files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The binary files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The files and folders to be ignored are determined from the built-in standard settings.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Operation parameters may have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap The name of the SAPUI5 repository "ZFIORIDEMO" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The package of the SAPUI5 Application "ZBC01" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Transport Request "DH1K900164" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The external Code Page Name "UTF8" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The acceptance of Unix style end of line markers in text files has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Unix style end of line markers in text files get accepted.
ERR! builder:custom deploy-to-abap The delta mode has been turned on.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Updating existing SAPUI5 ABAP repository ZFIORIDEMO
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Request DH1K900164 is not a change request
ERR! builder:custom deploy-to-abap Binary file manifest-bundle.zip has not been uploaded
ERR! builder:custom deploy-to-abap Request DH1K900164 is not a change request
ERR! builder:custom deploy-to-abap Binary file ncsupplierlist.zip has not been uploaded
ERR! builder:custom deploy-to-abap This syntax cannot be used for an object name
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Updating the Application Index *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Final outcome and/or log have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Cleanup done
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Cleanup done
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Done *
ERR! builder:custom deploy-to-abap SAP_Transaction:
ERR! builder:custom deploy-to-abap SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
ERR! builder:custom deploy-to-abap Deployment Failed.
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Running in regular mode, brief log
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap 16 Files found in Archive.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Parameters *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap The text files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The binary files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The files and folders to be ignored are determined from the built-in standard settings.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Operation parameters may have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap The name of the SAPUI5 repository "ZFIORIDEMO" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The package of the SAPUI5 Application "ZBC01" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Transport Request "DH1K900164" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The external Code Page Name "UTF8" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The acceptance of Unix style end of line markers in text files has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Unix style end of line markers in text files get accepted.
ERR! builder:custom deploy-to-abap The delta mode has been turned on.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Updating existing SAPUI5 ABAP repository ZFIORIDEMO
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Request DH1K900164 is not a change request
ERR! builder:custom deploy-to-abap Binary file manifest-bundle.zip has not been uploaded
ERR! builder:custom deploy-to-abap Request DH1K900164 is not a change request
ERR! builder:custom deploy-to-abap Binary file ncsupplierlist.zip has not been uploaded
ERR! builder:custom deploy-to-abap This syntax cannot be used for an object name
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Updating the Application Index *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Final outcome and/or log have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Cleanup done
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Cleanup done
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Done *
ERR! builder:custom deploy-to-abap SAP_Transaction:
ERR! builder:custom deploy-to-abap SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
Command deploy failed with error Request failed with status code 400
-----ERROR Message(End)---------

I tried the same command with test option (-tm) as below.
fiori deploy --noConfig -t XXXXXXX -u https://XXXXXXX.XXXX:XXXX -p ZXX01 -n ZFIORIDEMO -l nnn -e "FioriDeployTest" -y --username ABAP_USER --password ABAP_PASSWORD -tm

So I got the below error but it looks like that the files can be uploaded successfully.
Please let me know how to solve this error.

------ERROR Message start--------------
ERR! builder:custom deploy-to-abap Request failed with status code 403
ERR! builder:custom deploy-to-abap Test run has indicated no problems
ERR! builder:custom deploy-to-abap Test run has indicated no problems
ERR! builder:custom deploy-to-abap ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Running in test mode: Upload operations are indicated but not excuted, detailed log
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap 16 Files found in Archive.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Parameters *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap The text files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The binary files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The files and folders to be ignored are determined from the built-in standard settings.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Operation parameters may have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap The name of the SAPUI5 repository "ZFIORIDEMO" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The package of the SAPUI5 Application "ZBC01" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Transport Request "DH1K900164" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The external Code Page Name "UTF8" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The acceptance of Unix style end of line markers in text files has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Unix style end of line markers in text files get accepted.
ERR! builder:custom deploy-to-abap The delta mode has been turned on.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Operations *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap NONE          : Component-dbg.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : Component-preload.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : Component.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : controller/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : controller/Suppliers-dbg.controller.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : controller/Suppliers.controller.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : css/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : css/style.css (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : i18n/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : i18n/i18n.properties (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : index.html (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap UPLOAD FILE   : manifest-bundle.zip (Binary)
ERR! builder:custom deploy-to-abap NONE          : manifest.json (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : model/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : model/models-dbg.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : model/models.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap UPLOAD FILE   : ncsupplierlist.zip (Binary)
ERR! builder:custom deploy-to-abap NONE          : resources/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : resources/sap-ui-version.json (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : sap-ui-cachebuster-info.json (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : view/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : view/Suppliers.view.xml (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap DELETE FILE   : archive.zip
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Test run has indicated no problems
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Done *
ERR! builder:custom deploy-to-abap SAP_Transaction:
ERR! builder:custom deploy-to-abap SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
ERR! builder:custom deploy-to-abap Deployment Failed.
ERR! builder:custom deploy-to-abap Test run has indicated no problems
ERR! builder:custom deploy-to-abap Test run has indicated no problems
ERR! builder:custom deploy-to-abap ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Running in test mode: Upload operations are indicated but not excuted, detailed log
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap 16 Files found in Archive.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Parameters *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap The text files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The binary files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The files and folders to be ignored are determined from the built-in standard settings.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Operation parameters may have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap The name of the SAPUI5 repository "ZFIORIDEMO" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The package of the SAPUI5 Application "ZBC01" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Transport Request "DH1K900164" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The external Code Page Name "UTF8" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The acceptance of Unix style end of line markers in text files has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Unix style end of line markers in text files get accepted.
ERR! builder:custom deploy-to-abap The delta mode has been turned on.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Operations *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap NONE          : Component-dbg.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : Component-preload.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : Component.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : controller/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : controller/Suppliers-dbg.controller.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : controller/Suppliers.controller.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : css/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : css/style.css (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : i18n/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : i18n/i18n.properties (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : index.html (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap UPLOAD FILE   : manifest-bundle.zip (Binary)
ERR! builder:custom deploy-to-abap NONE          : manifest.json (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : model/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : model/models-dbg.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : model/models.js (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap UPLOAD FILE   : ncsupplierlist.zip (Binary)
ERR! builder:custom deploy-to-abap NONE          : resources/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : resources/sap-ui-version.json (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : sap-ui-cachebuster-info.json (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap NONE          : view/ (Folder already exists)
ERR! builder:custom deploy-to-abap NONE          : view/Suppliers.view.xml (Text) (Already up-to-date)
ERR! builder:custom deploy-to-abap DELETE FILE   : archive.zip
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Test run has indicated no problems
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Done *
ERR! builder:custom deploy-to-abap SAP_Transaction:
ERR! builder:custom deploy-to-abap SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
Command deploy failed with error Request failed with status code 403
-----ERROR Message(End)---------

**Comment by rodibrin** [comment]
@tomocci The transport request has been indicated as wrong:

`Request XXXXXXXXX is not a change request`

**Comment by tomocci** [comment]
@rodibrin 
Thank you.
I mistook the request and the request task.

But the different error was occurred.
What does it mean this error?
I have already confirmed this fiori app having no error in the Business Application Studio of BTP.

------ERROR Message start--------------
ERR! builder:custom deploy-to-abap Request failed with status code 400
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Running in regular mode, brief log
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap 16 Files found in Archive.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Parameters *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap The text files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The binary files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The files and folders to be ignored are determined from the built-in standard settings.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Operation parameters may have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap The name of the SAPUI5 repository "ZFIORIDEMO" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The package of the SAPUI5 Application "ZBC01" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Transport Request "DH1K900161" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The external Code Page Name "UTF8" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The acceptance of Unix style end of line markers in text files has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Unix style end of line markers in text files get accepted.
ERR! builder:custom deploy-to-abap The delta mode has been turned on.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Updating existing SAPUI5 ABAP repository ZFIORIDEMO
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap This syntax cannot be used for an object name
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Updating the Application Index *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Final outcome and/or log have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Cleanup done
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Done *
ERR! builder:custom deploy-to-abap SAP_Transaction:
ERR! builder:custom deploy-to-abap SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
ERR! builder:custom deploy-to-abap Deployment Failed.
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap SAPUI5 application ZFIORIDEMO was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Running in regular mode, brief log
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap 16 Files found in Archive.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Parameters *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap The text files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The binary files are identified using the standard settings.
ERR! builder:custom deploy-to-abap The files and folders to be ignored are determined from the built-in standard settings.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Operation parameters may have been adjusted.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Custom activities have been performed by class /UI5/CL_BADI_REPO_LOAD_SAMPLE: Parameters checked and adjusted
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap The name of the SAPUI5 repository "ZFIORIDEMO" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The package of the SAPUI5 Application "ZBC01" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Transport Request "DH1K900161" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The external Code Page Name "UTF8" has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap The acceptance of Unix style end of line markers in text files has been determined from the corresponding import parameter.
ERR! builder:custom deploy-to-abap Unix style end of line markers in text files get accepted.
ERR! builder:custom deploy-to-abap The delta mode has been turned on.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Updating existing SAPUI5 ABAP repository ZFIORIDEMO
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap This syntax cannot be used for an object name
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Updating the Application Index *
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap A BAdI implementation for /UI5/BADI_REPOSITORY_LOAD is active: Final outcome and/or log have been adjusted.
------ERROR Message End--------------

**Comment by tomocci** [comment]
I re-create Fiori app project again, So It works!

Thank you.
